# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: sample
  pool: 5
  username: markus
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: sample
  pool: 5
  username: markus
  password:
  timeout: 5000
